default_stages: [commit, push]
repos:
  - repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
      - id: black
        name: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies: ["flake8-bugbear"]
        name: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-case-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: no-commit-to-branch
#        args: ["--branch", "master"]
